#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'
cookbook 'apt'
cookbook 'vim'
cookbook 'git'
cookbook 'application'
cookbook 'mysql'
cookbook 'database'

#application_ruby dependencies
cookbook 'unicorn'
cookbook 'apache2'
cookbook 'passenger_apache2'
#

cookbook 'rvm',
  :git => 'https://github.com/fnichol/chef-rvm'